### ISSUE TITLE
Chart labels on post/user.html are swapped

### ISSUE THREAD

**Issue by mxmou** [shefwerld/shefwerld.github.io#9]
![image](https://user-images.githubusercontent.com/51849865/112299457-1b8bda80-8c98-11eb-9854-7bea6d0693e9.png)
![image](https://user-images.githubusercontent.com/51849865/112299486-20e92500-8c98-11eb-8631-ef141aab765d.png)

**Comment by mxmou** [comment]
@shefwerld

**Comment by shefwerld** [comment]
that will be fixed in the big funny update in a few days time

**Comment by mxmou** [comment]
The "big funny update" is here and this is still not fixed.

**Comment by mxmou** [comment]
Now it is.
